MVC_VIDEOS/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_VIDEOS;
using MVC_VIDEOS.Models;
using MVC_VIDEOS.Services;

namespace MVC_VIDEOS.Controllers
{
    public class GamesController : Controller
    {
        private bd_video_juegosEntities db = new bd_video_juegosEntities();

        // GET: Games
        public ActionResult Index()
        {
            return View(db.juegos.ToList());
        }

        [HttpPost]
        public ActionResult Search(GameFilterModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");

            return View(GamesDbService.LastClientRent(db, model.cedula));
        }

        // GET: Games/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            juegos juegos = db.juegos.Find(id);
            if (juegos == null)
            {
                return HttpNotFound();
            }
            return View(juegos);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_juego,nombre,descripcion,tipo")] juegos juegos)
        {
            if (ModelState.IsValid)
            {
                db.juegos.Add(juegos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(juegos);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            juegos juegos = db.juegos.Find(id);
            if (juegos == null)
            {
                return HttpNotFound();
            }
            return View(juegos);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LastClientRentViewModel model)
        {
            if (ModelState.IsValid)
            {

                GamesDbService.EditLastClientRent(db, model);
                return RedirectToAction("Index");
            }
            return View(db.juegos);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            juegos juegos = db.juegos.Find(id);
            if (juegos == null)
            {
                return HttpNotFound();
            }
            return View(juegos);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            juegos juegos = db.juegos.Find(id);
            db.juegos.Remove(juegos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_VIDEOS/Views/Games/Create.cshtml
@model MVC_VIDEOS.juegos

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>juegos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_VIDEOS/Views/Games/Delete.cshtml
@model MVC_VIDEOS.juegos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>juegos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC_VIDEOS/Views/Games/Details.cshtml
@model MVC_VIDEOS.juegos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>juegos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_juego }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC_VIDEOS/Views/Games/Edit.cshtml
@model MVC_VIDEOS.Models.LastClientRentViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>juegos</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Cedula)
    @Html.HiddenFor(model => model.id_juego)
    @Html.HiddenFor(model => model.id_tipo_juego)

    <div class="form-group">
        @Html.LabelFor(model => model.Cliente, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cliente, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cliente, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Juego, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Juego, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Juego, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tipojuego, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tipojuego, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tipojuego, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar Cambios" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_VIDEOS/Views/Games/Index.cshtml
@model IEnumerable<MVC_VIDEOS.juegos>

@{
    ViewBag.Title = "Index";
}

<!-- Search Bar -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <form class="form-inline" action="@Url.Action("Search","Games")" method="post">
        <input name="cedula" class="form-control mr-sm-2" type="text" placeholder="Cedula">
        <button class="btn btn-success" type="submit">Buscar</button>
    </form>
</nav>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id_juego }) |
                @Html.ActionLink("Details", "Details", new { id = item.id_juego }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id_juego })
            </td>
        </tr>
    }

</table>

MVC_VIDEOS/Views/Games/OSearch.cshtml
@using MVC_VIDEOS.Models;
@model IEnumerable<LastClientRentViewModel>

@{
    ViewBag.Title = "Buscar";
}

<script>
    var selectedRow = "@Guid.Empty";
    function changeSelectedIndex(id) {
        selectedRow = id;
        $("#mdl_cli_firstname").val($(`#${id} td input`)[0].value);
        $("#mdl_cli_lastname").val($(`#${id} td input`)[1].value);
        $("#mdl_game").val($(`#${selectedRow} td`)[2].innerHTML.trim());
        $("#mdl_game_des").val($(`#${selectedRow} td`)[3].innerHTML.trim());
    }
</script>

<h2>Buscar Cédula</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Juego)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description_juego)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipojuego)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha_alquiler)
        </th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr id="@item.Id">
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Juego)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description_juego)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tipojuego)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cantidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_alquiler)
        </td>
        <td>
            @*Html.ActionLink("Edit", "Edit", item.Cedula)*@
            <a data-toggle="modal" href="#editModal" onclick="changeSelectedIndex('@item.Id')">Edit</a>
        </td>
        <td><input hidden value="@item.Nombre" name="cli-firstname" /></td>
        <td><input hidden value="@item.Apellido" name="cli-lastname" /></td>
        <td><input hidden value="@item.id_juego" name="game-id" /></td>
        <td><input hidden value="@item.id_tipo_juego" name="ametype-id" /></td>
    </tr>
    }
</table>

<!-- Modal -->
<div class="modal fade" id="editModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "Games", FormMethod.Post))
                {
                    <input hidden name="cedula" />
                    <input hidden name="id_juego" />
                    <input hidden name="id_tipo_juego" />

                    <div class="form-group">
                        <label class="control-label col-md-2">Nombre</label>
                        <div class="col-md-10">
                            <input id="mdl_cli_firstname" class="form-control" type="text" name="nombre" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Apellido</label>
                        <div class="col-md-10">
                            <input id="mdl_cli_lastname" class="form-control" type="text" name="apellido" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Juego</label>
                        <div class="col-md-10">
                            <input id="mdl_game" class="form-control" type="text" name="juego" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Decripcion</label>
                        <div class="col-md-10">
                            <input id="mdl_game_des" class="form-control" type="text" name="description_juego" />
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

MVC_VIDEOS/Views/Games/Search.cshtml
@model MVC_VIDEOS.Models.LastClientRentViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Games",FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Detalle de ultimo juego alquilado por el cliente: @Model.Cliente</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Cedula)
    @Html.HiddenFor(model => model.id_juego)
    @Html.HiddenFor(model => model.id_tipo_juego)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Juego, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Juego, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Juego, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description_juego, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description_juego, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description_juego, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tipojuego, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tipojuego, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tipojuego, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fecha_alquiler, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fecha_alquiler, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.fecha_alquiler, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar Cambios" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}