MVC_VIDEOS/Models/alquileres.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC_VIDEOS.Models
{
    public class alquileres
    {
        [Key]
        public int id_alquiler { get; set; }
            public Nullable<long> ci_cliente { get; set; }
            public Nullable<int> id_juego { get; set; }
            public Nullable<System.DateTime> fecha_alquier { get; set; }
            public Nullable<int> id_tipo_juego { get; set; }

            public virtual clientes clientes { get; set; }
            public virtual juegos juegos { get; set; }
            public virtual tipo_juego tipo_juego { get; set; }
        
    }
}

MVC_VIDEOS/Controllers/AlquileresController.cs
using MVC_VIDEOS;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages.Html;


namespace MVC_VIDEOS.Controllers
{
    public class AlquileresController : Controller
    {
        // GET: Alquileres
        // instancia del objeto entity framework
        private bd_video_juegosEntities db = new bd_video_juegosEntities();
        public ActionResult Index()
        {
            ViewBag.alquileres = db.alquileres.ToList();
            
            return View();
        }

        // GET: Alquileres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var alquileres = db.alquileres.Find(id);
            if (alquileres == null)
            {
                return HttpNotFound();
            }

            return View(alquileres);

        }

        // GET: Alquileres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alquileres/Create
        [HttpPost]
        public ActionResult Create(alquileres alquileres)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.alquileres.Add(alquileres);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(alquileres);
            }
            catch
            {
                return View(alquileres);
            }
        }

        // GET: Alquileres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var alquileres = db.alquileres.Find(id);
            if (alquileres == null)
            {
                return HttpNotFound();
            }

            return View(alquileres);

        }

        // POST: Alquileres/Edit/5
        [HttpPost]
        public ActionResult Edit(alquileres alquileres)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(alquileres).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(alquileres);
            }
            catch
            {
                return View(alquileres);
            }

        }

        // GET: Alquileres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var alquileres = db.alquileres.Find(id);
            if (alquileres == null)
            {
                return HttpNotFound();
            }

            return View(alquileres);

        }

        // POST: Alquileres/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id, alquileres alquileres)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    alquileres = db.alquileres.Find(id);
                    if (alquileres == null)
                    {
                        return HttpNotFound();
                    }

                    db.alquileres.Remove(alquileres);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(alquileres);
            }
            catch
            {
                return View(alquileres);
            }

        }
    }
}

MVC_VIDEOS/Views/Alquileres/Create.cshtml
@using MVC_VIDEOS.Services
@model MVC_VIDEOS.alquileres

@{
    ViewBag.Title = "Create";

    var listClientes = new List<SelectListItem>();
    listClientes.AddRange(GamesDbService.AllClients()
        .Select(f => new SelectListItem()
        {
            Text = f.nombre + " " + f.apellidos,
            Value = f.cedula.ToString()
        }));

    var listJuegos = new List<SelectListItem>();
    listJuegos.AddRange(GamesDbService.AllGames()
        .Select(f => new SelectListItem()
        {
            Text = f.nombre,
            Value = f.id_juego.ToString()
        }));

    var listTiposJuegos = new List<SelectListItem>();
    listTiposJuegos.AddRange(GamesDbService.AllGamesTypes()
        .Select(f => new SelectListItem()
        {
            Text = f.descripcion,
            Value = f.id_tipo_juego.ToString()
        }));


}

<h2>Crear Nuevo</h2>

@using (Html.BeginForm("Create", "Alquileres", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>alquileres</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ci_cliente, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ci_cliente", listClientes, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ci_cliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_juego, "Juego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_juego", listJuegos, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_juego, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_alquier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_alquier, new { htmlAttributes = new { type = "date", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_alquier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_tipo_juego, "Tipo Juego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_tipo_juego", listTiposJuegos, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_tipo_juego, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC_VIDEOS/Views/Alquileres/Delete.cshtml
@model MVC_VIDEOS.alquileres

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar</h2>

<h3>Esta Seguro de Eliminar El registro?</h3>
<div>
    <h4>alquileres</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fecha_alquier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_alquier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clientes.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clientes.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.juegos.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.juegos.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_juego.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_juego.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC_VIDEOS/Views/Alquileres/Details.cshtml
@model MVC_VIDEOS.alquileres

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Alquileres</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fecha_alquier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_alquier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clientes.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clientes.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.juegos.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.juegos.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_juego.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_juego.descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_alquiler }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC_VIDEOS/Views/Alquileres/Edit.cshtml
@model MVC_VIDEOS.alquileres

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alquileres</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_alquiler)

        <div class="form-group">
            @Html.LabelFor(model => model.ci_cliente, "ci_cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ci_cliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ci_cliente, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.id_juego, "id_juego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_juego", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_juego, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha_alquier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha_alquier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha_alquier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_tipo_juego, "id_tipo_juego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_tipo_juego", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_tipo_juego, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC_VIDEOS/Views/Alquileres/Index.cshtml
@model IEnumerable<MVC_VIDEOS.alquileres>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.fecha_alquier)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.clientes.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.juegos.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipo_juego.descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in (List<alquileres>)ViewBag.alquileres)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.fecha_alquier)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.clientes.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.juegos.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tipo_juego.descripcion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_alquiler }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_alquiler }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_alquiler })
        </td>
    </tr>
}

</table>